---
# Required variables: file, url, params, and arch
- name: Vars
  debug:
    msg: "name {{ name }} url {{ url }} params {{ params }} arch {{ arch }}"
  tags:
    never, debug

- set_fact:
    repo_file: "{{ name }}.list"
    gpg_file: "{{ name }}.gpg"
- set_fact:
    gpg_file_path: "/etc/apt/trusted.gpg.d/{{ gpg_file }}"
    repo_file_path: "/etc/apt/sources.list.d/{{ repo_file }}"

- name: Find sources containing the same url that is to be added 
  find:
    path: /etc/apt/sources.list.d
    contains: "{{ url }}"
  register: existing_repo

- name: Data from duplicate repo files.
  debug:
    var: lookup('ansible.builtin.file', item)
  loop: "{{ existing_repo.files | map(attributes='path') | list }}"
  when: item |= repo_file
- name: Deleting duplicate repo files.
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ existing_repo.files | map(attributes='path') | list }}"
  when: item |= repo_file

- name: Ensuring /etc/apt/trusted.gpg.d is created correctly.
  file:
    path: /etc/apt/trusted.gpg.d
    state: directory
    mode: 0755
    owner: root
    group: root
  run_once: true

- name: "Adding pgp file {{ gpg_file }}."
  copy:
    src: "files/{{ gpg_file }}"
    dest: "{{ gpg_file_path }}"
    mode: 0644
    owner: root
    group: root

- set_fact:
    aptarch: "{{ ' arch=' + arch if (arch | length > 0) else ''}}"
- debug:
    msg: "Creating APT source file {{ repo_file_path }} with: deb [arch={{ arch }} signed-by={{ gpg_file_path }}] {{ url }} {{ params }}"
- copy:
    dest: "{{ repo_file_path }}"
    content: "deb [{{ aptarch }} signed-by={{ gpg_file_path }}] {{ url }} {{ params }}"
- name: Ensure repo permissions.
  file:
    path: "{{ repo_file_path }}"
    mode: 0644
    owner: root
    group: root
