---
- set_fact:
    name: trivy
    url: "https://aquasecurity.github.io/trivy-repo/deb"
    params: "{{ ansible_distribution_release }} main"
    arch: amd64
- name: Apt source for Opera
  include_tasks: add_repo.yaml
