---
- set_fact:
    file: packages.microsoft.gpg
    url: "https://packages.microsoft.com/repos/code"
    params: "stable non-free"
    arch: amd64
- name: Apt source for Opera
  include_tasks: add_repo.yaml
